"""create new model address

Revision ID: 34177b95ec6c
Revises: 083fd7d9bf90
Create Date: 2024-05-22 13:25:04.032297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34177b95ec6c'
down_revision = '083fd7d9bf90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=64), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_address_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_address_location'), ['location'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=False))
        batch_op.create_index(batch_op.f('ix_user_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_id'))
        batch_op.drop_column('password_hash')

    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_address_location'))
        batch_op.drop_index(batch_op.f('ix_address_id'))

    op.drop_table('address')
    # ### end Alembic commands ###
